//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUAI_personal_cabinet
{
    using System;
    using System.Collections.Generic;
    
    public partial class договор
    {
        public int ИД_договор { get; set; }
        public int ИД_клиента { get; set; }
        public int ИД_пользователя { get; set; }
        public string Тип { get; set; }
        public int Номер { get; set; }
        public System.DateTime Дата { get; set; }
        public string Файл { get; set; }
    }
}
