//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUAI_personal_cabinet
{
    using System;
    using System.Collections.Generic;
    
    public partial class клиент
    {
        public int ИД_клиента { get; set; }
        public string ФИО { get; set; }
        public string Адрес { get; set; }
        public Nullable<long> Телефон { get; set; }
        public string Эл_почта { get; set; }
        public string Документ_тип { get; set; }
        public string Документ_номер { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
    }
}
