//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUAI_personal_cabinet
{
    using System;
    using System.Collections.Generic;
    
    public partial class личн_услуги
    {
        public int ИД_лу { get; set; }
        public int ИД_кабинета { get; set; }
        public int ИД_услуги { get; set; }
        public System.DateTime Дата_услуги { get; set; }
        public bool Состояние { get; set; }
    }
}
