//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUAI_personal_cabinet
{
    using System;
    using System.Collections.Generic;
    
    public partial class личный_кабинет
    {
        public int ИД_кабинета { get; set; }
        public int ИД_клиента { get; set; }
        public int ИД_тарифа { get; set; }
        public Nullable<System.DateTime> Дата_тарифа { get; set; }
    }
}
