//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUAI_personal_cabinet
{
    using System;
    using System.Collections.Generic;
    
    public partial class пользователь
    {
        public int ИД_пользователя { get; set; }
        public string Уровень { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int ИД_клиента { get; set; }
    }
}
