//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUAI_personal_cabinet
{
    using System;
    using System.Collections.Generic;
    
    public partial class тариф
    {
        public int ИД_тарифа { get; set; }
        public int ИД_пользователя { get; set; }
        public Nullable<int> Тип1 { get; set; }
        public Nullable<int> Тип2 { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
    }
}
